### PR TITLE
Drop fork and update to latest sentry-go

### LINKED ISSUE #36: Requires use of github.com/cockroachdb/sentry-go
This package uses its own fork of [sentry-go](https://github.com/getsentry/sentry-go) which means a user of this package has to use the forked version when initializing the sentry client. Is that the accepted practice around this?

### LINKED ISSUE #41: Update to Sentry SDK v0.7.0
Sentry is telling us that 0.6.1 is oudated.

### PR DESCRIPTION
**Pull request by jhchabran**
Fixes #36 
Fixes #41 

This PR drops the fork and updates to the latest stable `sentry-go` release (v0.12.0). 

Because that's quite a jump, even though there are no breaking changes, I did some manual tests, to make sure everything still looks correct (see the folds below). 

Tests are green locally. 

<details>
  <summary>Quick script I used to QA</summary>

`cmd/qa/main.go`

```go
package main

import (
	"fmt"
	"log"
	"os"
	"time"

	"github.com/cockroachdb/errors"
	"github.com/getsentry/sentry-go"
)

func Foo(i int) {
	Bar(i + 1)
}

func Bar(i int) {
	Baz(i + 1)
}

func Baz(i int) {
	_, err := os.Open("non-existing.ext")
	e := errors.Wrap(err, "Doing some QA")
	errors.ReportError(e)
}

func Event() {
	_, err := os.Open("different-non-existing.ext")
	e := errors.Wrap(err, "Doing some QA")

	event, extraDetails := errors.BuildSentryReport(e)
	fmt.Printf("%#v\n", extraDetails)

	sentry.WithScope(func(scope *sentry.Scope) {
		scope.SetExtras(extraDetails)
		sentry.CaptureEvent(event)
	})
}

func main() {
	err := sentry.Init(sentry.ClientOptions{})
	if err != nil {
		log.Fatalf("sentry.Init: %s", err)
	}

	Foo(2)
	Event()
	defer sentry.Flush(5 * time.Second)
	fmt.Println("bye")
}
```
</details>

<details>
  <summary>Screenshots</summary>
  
image
image
</details>

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/errors/92)

### CODE REVIEW

**Review by bobheadxi — APPROVED** [review]
nice, thanks for extensively manual testing this!

**Comment by knz** [comment]
Ok, this change is amazing. I had feared that by upgrading the dependency, we'd need to also change the API inside the errors library. I'm glad this is not the case.

That being said, before we merge this we will also want to test it out with CockroachDB and our Sentry account, to verify the issues get filed accurately. I will schedule some work on that direction and keep you updated.

**Review by knz — COMMENTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/errors/92)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jhchabran)

**Comment by jhchabran** [comment]
> Ok, this change is amazing. I had feared that by upgrading the dependency, we'd need to also change the API inside the errors library. I'm glad this is not the case.

Thank you! It really went nicely, though I have to mention that I pulled my hairs on the tests because I had cloned the repo under a different name `git clone ... newname` which broke them because they do depend on the folder being named `errors`. I'm writing this down here just in case does the same mistake as me 😵‍💫 

> That being said, before we merge this we will also want to test it out with CockroachDB and our Sentry account, to verify the issues get filed accurately. I will schedule some work on that direction and keep you updated. 

I totally understand and I'm really grateful for you taking the time to do this soon. I know that testing these things can be really annoying, so feel free to reach out if I can help with anything!

**Comment by huzhao37** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

**Comment by knz** [comment]
> This seems to imply I have something else to do. Is that the case? I'm not sure to see what else I could do here!

nah you're good.

**Comment by knz** [comment]
CI says it's fine apparently?
image

**Comment by knz** [comment]
This works as per https://github.com/cockroachdb/cockroach/issues/76439

**Review by knz — APPROVED** [review]

**Pull request merged**
