### PR TITLE
Tweak import paths of .proto files in errorspb

### PR DESCRIPTION
**Pull request by rickystewart**
This makes imports consistent both within this repository as well as in
the main CockroachDB repo. This simplifies the Bazel migration as seen
in https://github.com/cockroachdb/cockroach/pull/57974.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/errors/60)

### CODE REVIEW

**Comment by knz** [comment]
LGTM thanks

**Comment by tooolbox** [comment]
Out of curiosity, is this change backwards compatible, i.e. markers encoded with the old registered name will properly decode with the new registered name, and vice versa?

**Comment by rickystewart** [comment]
To my knowledge, yes (and this change has been live at CockroachDB master for more than 2 weeks, so I imagine that any issues would have been noticed by now).

**Comment by knz** [comment]
> markers encoded with the old registered name will properly decode with the new registered name, and vice versa?

Thanks for noticing. I agree we need to explicitly check this.

> I imagine that any issues would have been noticed by now).

No not necessarily. Last time we broke something in that area, we only noticed when a customer encountered a production outage after an upgrade :sob:

**Comment by knz** [comment]
@rickystewart also you don't need to do anything about this; I will do the investigation and fix the fallout if any.

**Pull request merged**
