### PR TITLE
Fix support for Go 1.16.

### PR DESCRIPTION
**Pull request by knz**
Found while working on #67.

In Go 1.16, the error type `os.PathError` was moved to a different
package. This requires a type migration to be present to ensure
the error can be properly decoded across processes built with
different go versions.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/errors/68)

### CODE REVIEW

**Review by erikgrinaker — COMMENTED** [review]
> Reviewed 19 of 19 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/errors/68)* status: all files reviewed, 2 unresolved discussions (waiting on @knz)

___
*[fmttests/datadriven_test.go, line 506 at r1](https://reviewable.io/reviews/cockroachdb/errors/68#-MYAyooy19cMe7XBQrpr:-MYAyooz8nwTVGMsTox5:b-kj79uc) ([raw file](https://github.com/cockroachdb/errors/blob/9347dc2ba67a90c9ef3a5c3f7d94dcd65436269a/fmttests/datadriven_test.go#L506)):*
> ```Go
> 
> 				// Needed as long as pre-go1.16 is supported to build.
> 				needOsPathRedirect := false
> ```

Is this really necessary? Isn't it always safe and appropriate to call  `fakeGo116` regardless of test?
___
*[fmttests/datadriven_test_pre116.go, line 21 at r1](https://reviewable.io/reviews/cockroachdb/errors/68#-MYAzHWs7tMQMkTvZawC:-MYAzHWs7tMQMkTvZawD:b-fxd9z7) ([raw file](https://github.com/cockroachdb/errors/blob/9347dc2ba67a90c9ef3a5c3f7d94dcd65436269a/fmttests/datadriven_test_pre116.go#L21)):*
> ```Go
> import "strings"
> 
> func fakeGo116(s string) string {
> ```

Could we derive this from the migration? Duplicating the mapping in both code and tests seems unfortunate.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/errors/68)* status: all files reviewed, 2 unresolved discussions (waiting on @erikgrinaker)

___
*[fmttests/datadriven_test.go, line 506 at r1](https://reviewable.io/reviews/cockroachdb/errors/68#-MYAyooy19cMe7XBQrpr:-MYB0jMk2DmbD4xTpqX3:b-qu6n94) ([raw file](https://github.com/cockroachdb/errors/blob/9347dc2ba67a90c9ef3a5c3f7d94dcd65436269a/fmttests/datadriven_test.go#L506)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Is this really necessary? Isn't it always safe and appropriate to call  `fakeGo116` regardless of test?
</blockquote></details>

Good point. Done.
___
*[fmttests/datadriven_test_pre116.go, line 21 at r1](https://reviewable.io/reviews/cockroachdb/errors/68#-MYAzHWs7tMQMkTvZawC:-MYB0kPN3ubXFMc3vnG4:b3zrcrh) ([raw file](https://github.com/cockroachdb/errors/blob/9347dc2ba67a90c9ef3a5c3f7d94dcd65436269a/fmttests/datadriven_test_pre116.go#L21)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Could we derive this from the migration? Duplicating the mapping in both code and tests seems unfortunate.
</blockquote></details>

1. The way I see it is that the migration will remain forever, but we'll remove the logic in tests when we stop testing in pre-1.16.
2. I think optimizing this is premature. I do my factoring at the 3rd time, not the 2nd.

**Review by erikgrinaker — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/errors/68#-:-MYB2QK7-D4WuDON-ExP:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @knz)

___
*[fmttests/datadriven_test_pre116.go, line 21 at r1](https://reviewable.io/reviews/cockroachdb/errors/68#-MYAzHWs7tMQMkTvZawC:-MYB2HRwC65aU80ORbHP:b-rf09q) ([raw file](https://github.com/cockroachdb/errors/blob/9347dc2ba67a90c9ef3a5c3f7d94dcd65436269a/fmttests/datadriven_test_pre116.go#L21)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

1. The way I see it is that the migration will remain forever, but we'll remove the logic in tests when we stop testing in pre-1.16.
2. I think optimizing this is premature. I do my factoring at the 3rd time, not the 2nd.
</blockquote></details>

That's fair.

**Comment by knz** [comment]
thanks!

**Pull request merged**
