### PR TITLE
Update to gogoproto 1.3.

### PR DESCRIPTION
**Pull request by knz**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/errors/67)

### CODE REVIEW

**Review by erikgrinaker — APPROVED** [review]
> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/errors/67)* status: all files reviewed, 1 unresolved discussion (waiting on @knz)

___
*[Makefile.update-protos, line 7 at r1](https://reviewable.io/reviews/cockroachdb/errors/67#-MYAMXwK-dW_rII4Yttb:-MYAMXwK-dW_rII4Yttc:b-67ov28) ([raw file](https://github.com/cockroachdb/errors/blob/fc9a5bd7dc3e5e0b9a13aad0db3532c270ece02e/Makefile.update-protos#L7)):*
> ```
> #   go get github.com/cockroachdb/protoc-gen-gogoroach
> #   go get github.com/gogo/protobuf/types
> #   go get github.com/gogo/protobuf/protoc-gen-gogo
> ```

Could we somehow lock these versions in `go.mod`, even though they're build tools rather than direct dependencies?

**Comment by knz** [comment]
> Could we somehow lock these versions in go.mod, even though they're build tools rather than direct dependencies?

Maybe; how should I do this?

**Comment by erikgrinaker** [comment]
>Maybe; how should I do this?

You could do something like this: https://marcofranssen.nl/manage-go-tools-via-go-modules/

The Go team approves: https://github.com/golang/go/issues/25922#issuecomment-402918061

**Comment by erikgrinaker** [comment]
Also, I seem to recall that @tooolbox had some ideas on handling build-time dependencies.

**Comment by erikgrinaker** [comment]
Cool, let's revisit later.

**Pull request merged**
