### PR TITLE
Switch to sentry-go when building the reports

### PR DESCRIPTION
**Pull request by yuzefovich**
Previously, we were using getsentry/raven-go to populate the reports for
Sentry. However, that tool has become obsolete. This commit switches to
using getsentry/sentry-go.

There are some differences in the API, and I made the following changes:
- now there can be multiple "exceptions" specified in the sentry event
  (previously, only one was allowed).
- "message" field will now be populated with the "head message" (a short
  description of the first error)
- "long message" will be included in Extra.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/errors/20)

### CODE REVIEW

**Comment by knz** [comment]
Thank you!

For clarity, can you copy-paste a screenshot of a sentry report generated with the new code?

cc @tooolbox - I wasn't expected we'd invest in this so soon, but here you are.

**Comment by yuzefovich** [comment]
I ran the test with `DSN` specified as `cockroachdb` project, and here is what I got:

screencapture-sentry-io-organizations-cockroach-labs-issues-1402512507-events-ec150053681548f6b2ea2fc75c994614-2019-12-22-16_38_56

(The [link](https://sentry.io/share/issue/2f3810c5e6e44354bbd62743a88f4380/) to the event)

**Comment by knz** [comment]
Thank you this looks good overall. However I'd like to see how this impacts the reporting of SQL errors. I would recommend to operate as follows:

1. make sure your new code is in your $GOPATH
2. take your cockroachdb work dir and `rm -rf vendor/github.com/cockroachdb/errors`
3. build binary
4. make it report a SQL error (e.g. `crdb_internal.force_error('XX000', 'woops')`
5. see how the sentry report looks like.

Is the SQL statement included? Is it clear from the sentry message that the error was generated with `force_error`?

If yes then this is good to go.

**Comment by yuzefovich** [comment]
Thanks for the pointers!

I made some modifications to `cockroach` to use `sentry-go` as well, and here is the report
screencapture-sentry-io-organizations-cockroach-labs-issues-1404688926-2019-12-24-09_54_54

(and the [link](https://sentry.io/share/issue/aca4f08b579344908bbd0dee1109ef63/))

I think it looks good, right?

**Comment by knz** [comment]
Oh yeah that looks awesome. LGTM!

**Comment by knz** [comment]
After you merge this we need to bump the version because this is a backward-incompatible API change. You can add a tag for `v1.3`.

**Comment by yuzefovich** [comment]
TFTR!

I'll push a new tag momentarily.

**Pull request merged**
