### PR TITLE
add IsType() to check if an error of a type is contained in an error

### PR DESCRIPTION
**Pull request by ajwerner**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/errors/19)

### CODE REVIEW

**Comment by knz** [comment]
So can you spell out with some words (e.g in the commit message) what is the use case for the interface compatibility check?

**Comment by ajwerner** [comment]
I guess we don't need it. The first type of error I reached for when testing was  `net.Error` which I realized is an interface and then realized there was no way to use this to search for an interface type. Maybe it's not worth the complexity. I'll roll it back.

**Comment by ajwerner** [comment]
I added a second commit with `IsInterface()` and added more language to the commit messages. I'm a little hesitant about the panics in `IsInterface()`.

**Comment by knz** [comment]
LGTM.

> I'm a little hesitant about the panics in IsInterface().

The alternative would be to return a silent false, which would paper over programmer mistakes, or return an error next to the boolean, which would be cumbersom (and costly in the common case). The advantage of your code is that a mistake will make it panic immediately. It's not too bad.

**Pull request merged**
